config:
  target: 'http://localhost:5000'
  phases:
    # Warm-up phase
    - duration: 60
      arrivalRate: 10
      name: "Warm up"
    # Ramp up phase
    - duration: 120
      arrivalRate: 50
      rampTo: 200
      name: "Ramp up load"
    # Sustained load phase
    - duration: 300
      arrivalRate: 200
      name: "Sustained load"
    # Peak load phase
    - duration: 180
      arrivalRate: 500
      name: "Peak load"
    # Cool down phase
    - duration: 60
      arrivalRate: 100
      name: "Cool down"
  defaults:
    headers:
      Content-Type: 'application/json'
  plugins:
    metrics-by-endpoint:
      useOnlyRequestNames: true

scenarios:
  - name: "API Health Check"
    weight: 20
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200
            - hasHeader: "content-type"
            - contentType: "application/json"

  - name: "Get Products"
    weight: 30
    flow:
      - get:
          url: "/api/products"
          expect:
            - statusCode: 200
            - hasHeader: "content-type"
            - contentType: "application/json"

  - name: "Get Featured Products"
    weight: 25
    flow:
      - get:
          url: "/api/products/featured"
          expect:
            - statusCode: 200
            - hasHeader: "content-type"
            - contentType: "application/json"

  - name: "Search Products"
    weight: 15
    flow:
      - get:
          url: "/api/products/search"
          qs:
            q: "water bottle"
            category: "water-bottles"
          expect:
            - statusCode: 200
            - hasHeader: "content-type"
            - contentType: "application/json"

  - name: "Get Single Product"
    weight: 10
    flow:
      - get:
          url: "/api/products/{{ $randomString() }}"
          expect:
            - statusCode: [200, 404]
            - hasHeader: "content-type"
            - contentType: "application/json"
